# -*- coding: utf-8 -*-
"""Matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KzLwN2WuFLiDPu0BnOyONr7xD2jXEU1s
"""

import matplotlib.pyplot as plt
import pandas as pd

x = [1,2,3]
y = [4,5,6]

plt.plot(x,y)
plt.grid()
plt.show()

data = {
    "Salary":[200,300,400,500,100,500,200,900,1000]
}

df = pd.DataFrame(data)
df.head()

df.shape

plt.plot(df["Salary"],color='Red',marker='o',linestyle=':')
plt.show()

plt.hist(df["Salary"],bins=9,color='Red')
plt.show()

plt.boxplot(df["Salary"])
plt.show()

df["Dept"] = ['HR','IT','Finance','HR','HR','IT','Finance','HR','Finance']
df.shape

df.head()

count = df["Dept"].value_counts()
print(count)

plt.pie(count, labels=count.index, autopct="%1.1f",explode=[0,0.1,0])
plt.axis('equal')
plt.show()

plt.bar(count.index,count,color=["Green","Red","Black"])
plt.show()

df["Age"] = [22,23,24,25,26,27,21,29,28]
df.head()

plt.scatter(df["Age"],df["Salary"],color="Orange")
plt.show()

sort_age = df.sort_values("Age")

plt.plot(sort_age["Age"],df["Salary"],color="Red",marker="o")
plt.show()

plt.bar(sort_age["Age"],df["Salary"],color="Green")
plt.show()

